apiVersion: v1
kind: Namespace
metadata:
  name: openfaasdev
  labels:
    role: openfaas-system
    access: openfaas-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaasdev-fn
  labels:
    istio-injection: enabled
    role: openfaas-fn
