---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaasdev
    component: basic-auth-plugindev
  name: basic-auth-plugindev
  namespace: "openfaasdev"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: basic-auth-plugindev
