---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaasdev
    component: gatewaydev
  name: gatewaydev
  namespace: "openfaasdev"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8180
      targetPort: 8180
      protocol: TCP
    - name: metrics
      port: 8182
      targetPort: 8182
      protocol: TCP
  selector:
    app: gatewaydev
