---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaasdev
    component: gatewaydev
  name: gatewaydev-external
  namespace: "openfaasdev"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8180
      protocol: TCP
      targetPort: 8180
      nodePort: 31212
  selector:
    app: gatewaydev
