---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaasdev
    component: prometheusdev
  name: prometheusdev-external
  namespace: "openfaasdev"
spec:
  type: NodePort
  ports:
    - name: http
      port: 9190
      protocol: TCP
      targetPort: 9190
      nodePort: 31443
  selector:
    app: prometheusdev
