---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaasdev
    component: prometheusdev
  name: prometheusdev
  namespace: "openfaasdev"
spec:
  type: ClusterIP
  ports:
    - port: 9190
      protocol: TCP
      targetPort: 9190
  selector:
    app: prometheusdev
