[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/morikuni/aec"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.1"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.12.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.5"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.5"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "v1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.3"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/docker/docker-credential-helpers"
  version = "v0.6.3"

[[constraint]]
  name = "github.com/drone/envsubst"
  version = "v1.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.1"

[[constraint]]
  name = "github.com/alexellis/go-execute"
  version = "0.3.0"

