provider:
  name: openfaas
  gateway: http://127.0.0.1:8080  # can be a remote server

## Note for Kubernetes memory specifications:
## Run: `sed -ie s/40m/40Mi/g stack.yml`

functions:
  url-ping:
    lang: python
    handler: ./sample/url-ping
    image: ${DOCKER_USER:-alexellis}/faas-url-ping:0.2
#    limits:
#      memory: 40m
#    requests:
#      memory: 40m

  stronghash:
    skip_build: true
    image: functions/alpine:latest
    fprocess: "sha512sum"
#    limits:
#      memory: 40m
#    requests:
#      memory: 40m

  nodejs-echo:
    lang: node
    handler: ./sample/nodejs-echo
    image: alexellis/faas-nodejs-echo:0.1
#    limits:
#      memory: 40m
#    requests:
#      memory: 40m

  # curl 127.0.0.1:8080/function/shrink-image --data-binary @big.png > smaller.png
  shrink-image:
    lang: dockerfile
    handler: ./sample/imagemagick
    image: functions/resizer:0.1
    fprocess: "convert - -resize 50% fd:1"
#    limits:
#      memory: 40m
#    requests:
#      memory: 40m

  ruby-echo:
    lang: ruby
    handler: ./sample/ruby-echo
    image: alexellis/ruby-echo:0.2
#    limits:
#      memory: 40m
#    requests:
#      memory: 40m

